config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  delete '/users/sign_out' => 'devise/sessions#destroy'
  resources :friends do
    collection do
      get 'search' => 'friends#search'
    end
  end
  root to: 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  def search
    @search_friends = current_user.friends.where(first_name: "#{params[:name]}") 
  end

  def correct_user
    @friend_in_user = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: 'Not authorized to edit this friend' if @friend_in_user.nil?
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
  <%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <%= form.text_field :first_name, placeholder: "First name..." %><br/><br/>
    <%= form.text_field :last_name, placeholder: "Last name..." %><br/><br/>
    <%= form.text_field :email, placeholder: "Email..." %><br/><br/>
    <%= form.text_field :phone, placeholder: "Phone number..." %><br/><br/>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %><br/><br/>
    <div class="actions">
      <%= link_to 'Back', friends_path, class: "btn btn-secondary" %>
      <%= form.submit class: "btn btn-secondary" %>
    </div>
  </div>

<% end %>

app/views/friends/_namesearch.html.erb
<form action="/friends/search">
  <input type="text" name="name">
  <%= button_to "Search", search_friends_path, type: :submit %>
</form>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>

<%= render 'form', friend: @friend %>

app/views/friends/index.html.erb
<h3>Friends list</h3>
<div>
  <%= render 'friends/namesearch' %>

  <table class="table table-striped table-light table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= button_to "Delete", friend, method: :delete, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

app/views/friends/search.html.erb
<h3>Searched friends</h3>
<div>
  <%= render 'friends/namesearch' %>

  <table class="table table-striped table-light table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @search_friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= button_to "Delete", friend, method: :delete, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/friends/show.html.erb
<h2>Friend details</h2>
<p class="container-fluid">
  <p>
    <strong>First name:</strong>
    <%= @friend.first_name %>
    </p>
    <p>
      <strong>Last name:</strong>
      <%= @friend.last_name %>
    </p>
    <p>
      <strong>Email:</strong>
      <%= @friend.email %>
    </p>
    <p>
      <strong>Phone:</strong>
      <%= @friend.phone %>
    </p>
  </p>
  </p>
    <%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-secondary" %> |
    <%= link_to 'Back', friend_path, class: "btn btn-secondary" %><br/><br/>
    <%= button_to 'Delete', friend_path(@friend), method: :delete, class: "btn btn-danger" %>
  </p>
</p>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'About us', home_about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Friends', friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Add a new friend', new_friend_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              My profile
            </a>
            <ul class="dropdown-menu bg-light" aria-labelledby="navbarDropdownMenuLink">
              <li><%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %></li>
              <li><%= button_to 'Edit profile', edit_user_registration_path, method: :get, class: 'btn btn-secondary' %></li>
              <%# <li><%= button_to 'Delete my account', user_registration_path, method: :delete, class: "btn btn-danger" %>
              <li><button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteUserModal">
                    Cancel my account
                  </button>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Unhappy with the account?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h2>Are you not happy with our services, or do you want the app no more?</h2>
        <h4>We are sad to hear that!</h4>
      </div>
      <div class="modal-footer">
        <%= button_to "Cancel my account", user_registration_path, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<p>About page</p>

app/views/home/index.html.erb
<h1>Welcome to our Friends app home page</h1><br/><br/>
<% if user_signed_in? %>
    <h4>Welcome</h4>
    <%= current_user.email %>
<% else %>
    <p>If you are already a member, please sign in to the app</p>
    <p>If you are not yet a user, please sign up to use the app</p>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>FriendsApp</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <br/><br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <div class= 'container'>
      <%= yield %><br/><br/>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>